channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal=5.2.4
  - python=3.6
  - bowtie2=2.3.4.3
  - fastqc=0.11.8
  - multiqc=1.6
  - bedtools=2.26.0
  - rseg=0.4.9
  - samtools=1.7
  - star=2.6.0b
  - ucsc-bedclip=357
  - ucsc-bedgraphtobigwig=357
  - ucsc-bigwigaverageoverbed=357